# roles/deploy_f5_tenants_to_velos/tasks/main.yml

- name: Validate group sizes and create deployment pairs
  ansible.builtin.include_tasks: validate_and_zip.yml

- name: Run deployment tasks per pair
  ansible.builtin.include_tasks: deploy_pair.yml
  loop: "{{ create_f5_os_tenant_ha_deployment_pairs }}"
  loop_control:
    loop_var: create_f5_os_tenant_ha_pair
#  when: hostvars[create_f5_os_tenant_ha_pair[0]].inventory_hostname in inventory_hostname
