# roles/deploy_f5_tenants_to_velos/tasks/main.yml

- name: Validate inventory groups and build source-destination pairs
  ansible.builtin.include_tasks: validate_and_zip.yml

- name: Loop through deployment pairs (wrapper)
  ansible.builtin.include_tasks: deploy_pair_wrapper.yml
  loop: "{{ create_f5_os_tenant_ha_deployment_pairs }}"
  loop_control:
    loop_var: create_f5_os_tenant_ha_pair
