- name: Validate source and destination group counts
  ansible.builtin.fail:
    msg: "Groups '{{ create_f5_os_tenant_ha_source_group }}' and '{{ create_f5_os_tenant_ha_destination_group }}' must have the same number of hosts"
  when: groups[create_f5_os_tenant_ha_source_group] | length != groups[create_f5_os_tenant_ha_destination_group] | length

- name: Zip source and destination group hosts
  ansible.builtin.set_fact:
    create_f5_os_tenant_ha_deployment_pairs: >-
      {{ groups[create_f5_os_tenant_ha_source_group] | zip(groups[create_f5_os_tenant_ha_destination_group]) | map('list') | list }}
