---

- name: Create Backup File Directory (Execution Engine)
  ansible.builtin.file:
    path: "{{ backup_path }}"
    state: directory
    mode: '0755'
  delegate_to: localhost

- name: Use find to get the files list which you want to copy/fetch
  ansible.builtin.find:
    paths: "{{ backup_path }}"
    patterns: "master_key_*.json"
  register: file_fetch
  delegate_to: localhost

- name: Use find to get the files list which you want to copy/fetch
  ansible.builtin.find:
    paths: "{{ backup_path }}"
    patterns: "inventory_*.json"
  register: file_2_fetch
  delegate_to: localhost

- name: Use find to get the files list which you want to copy/fetch
  ansible.builtin.find:
    paths: "{{ backup_path }}"
    patterns: "*.ucs"
  register: file_3_fetch
  delegate_to: localhost

- name: Use fetch to get the files
  ansible.builtin.fetch:
    src: "{{ item.path }}"
    dest: "{{ backup_path }}"
    flat: true
  with_items:
    - "{{ file_fetch.files }}"
    - "{{ file_2_fetch.files }}"
    - "{{ file_3_fetch.files }}"
  delegate_to: localhost