---

- name: Test Code
  hosts: f5_destination_tenant
  connection: local
  gather_facts: false
  vars:
    provider:
      server: "{{ ansible_host }}"
      user: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      server_port: 443
      no_f5_teem: true
      validate_certs: false

  tasks:

    - name: Collect BIG-IP information
      f5networks.f5_modules.bigip_device_info:
        gather_subset:
          - as3
          - virtual-servers
          - ltm-pools
        provider: "{{ provider }}"
        partition: "Tenant-002"
      register: info
      delegate_to: localhost

    - name: debug
      ansible.builtin.debug:
        var: info
