---
- name: Remove all Tenants
  hosts: lb
  connection: httpapi
  gather_facts: false

  vars:
    ansible_httpapi_password: "{{ ansible_password }}"
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: "{{ server_port }}"
    ansible_httpapi_use_proxy: false

  tasks:

    - name: Remove all tenants - AS3
      f5networks.f5_bigip.bigip_as3_deploy:
        tenant: all
        state: absent
