---

- name: Test Code
  hosts: f5_destination_tenant
  connection: local
  gather_facts: false
  vars:
    provider:
      server: "{{ ansible_host }}"
      user: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      server_port: "{{ server_port }}"
      no_f5_teem: true
      validate_certs: false

  tasks:

    - name: Collect BIG-IP information
      f5networks.f5modules.bigip_device_info:
        gather_subset:
          - virtual-servers
          - ltm-pools
        provider: "{{ provider }}"
      delegate_to: localhost
