---
- name: "[06] Build and Start Destination F5"
  hosts: bastion-backup
  gather_facts: false
  roles:
    - copy_files_to_execution_engine

- name: "[07] Build and Start Destination F5"
  hosts: f5_destination_partition
  connection: httpapi
  gather_facts: false
  roles:
    - create_f5_os_tenant
    - start_f5_os_tenant

- name: "[08] Setup and Restore Destination BIG-IP Crypto Files"
  hosts: f5_destination_tenant
  connection: local
  gather_facts: false
  roles:
    - set_admin_password_shell
    - restore_crypto_keys

- name: "[09] Copy Source BIG-IP UCS File to Destination BIG-IP"
  hosts: f5_destination_tenant
  connection: httpapi
  gather_facts: false
  roles:
    - copy_ucs_file

- name: "[10] Restore Destination BIG-IP UCS"
  hosts: f5_destination_tenant
  gather_facts: false
  roles:
    - restore_ucs

- name: "[11] Wait for UCS Restore to Complete"
  hosts: f5_destination_tenant
  connection: httpapi
  gather_facts: false
  roles:
    - restore_ucs_wait
